# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14

modify_font cell_width 95%

# Window
window_border_width 1
hide_window_decorations titlebar-and-corners
window_title_format "Ghostty • {title}"
window_margin_width 2
window_padding_width 2
placement_strategy center

# Hide mouse while typing
mouse_hide_wait -0.1

# silence..
enable_audio_bell no


# Background Blur
background_opacity 0.89
background_blur 18

# Tab
tab_bar_align center
tab_bar_style separator
tab_bar_margin_width 8.0
tab_bar_margin_height 5.0
tab_separator ""
tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}█{fmt.fg._abb2bf}{fmt.bg._5c6370} {index} {tab.active_oldest_exe} {fmt.fg._5c6370}{fmt.bg.default}█ "

active_tab_title_template "{fmt.fg._eee8d5}{fmt.bg.default}█{fmt.fg.default}{fmt.bg._eee8d5}*{index}:{tab.active_oldest_exe} {fmt.fg._eee8d5}{fmt.bg.default}█ "
active_tab_font_style bold

# Move between tabs
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5

# Ligatures
enable_ligatures yes

macos_option_as_alt yes

# Blur / Transparency
blur_background yes
blur_radius 30  # adjust for stronger/weaker blur

include theme.conf
