# # Dracula color theme.
# background #0e1419
# foreground #f8f8f2
# selection_foreground #ffffff
# selection_background #44475a
# url_color #8be9fd
# color0 #44475a
# color8 #6272a4
# color1 #ff5555
# color9 #ff6e6e
# color2 #50fa7b
# color10 #69ff94
# color3 #f1fa8c
# color12 #ffffa5
# color4 #bd93f9
# color12 #d6acff
# color5 #ff79c6
# color13 #ff92df
# color6 #8be9fd
# color14 #a4ffff
# color7 #f8f8f2
# color15 #ffffff
# cursor #f8f8f2
# cursor_text_color background
# mark1_foreground #282a36
# mark1_background #ff5555
# active_border_color #f8f8f2
# inactive_border_color #6272a4



# Solarized Dark theme for Kitty

foreground            #839496
background            #031219
selection_foreground  #ffffff
selection_background  #44475a
mark1_background #ff5555
active_border_color #f8f8f2
inactive_border_color #6272a4


url_color             #8be9fd

cursor_text_color background

# black
color0  #073642
color8  #002b36

# red
color1  #dc322f
color9  #cb4b16

# green
color2  #859900
color10 #586e75

# yellow
color3  #b58900
color11 #657b83

# blue
color4  #268bd2
color12 #839496

# magenta
color5  #d33682
color13 #6c71c4

# cyan
color6  #2aa198
color14 #93a1a1

# white
color7  #eee8d5
color15 #fdf6e3
